# Generated by Django 3.2.2 on 2021-05-08 13:12

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', markdownx.models.MarkdownxField()),
                ('isOpen', models.BooleanField()),
            ],
        ),
    ]
